name: ci-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U "poetry<=1.8.0"
          poetry config virtualenvs.create false
          poetry install
      - name: Testing
        run: |
          python -m pytest tests

  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U "poetry<=1.8.0"
          poetry config virtualenvs.create false
          poetry install
      - name: Testing
        run: |
          python -m pytest --cov=papers tests
          python -m codecov

  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U "poetry<=1.8.0"
          poetry config virtualenvs.create false
          poetry install
      - name: Testing
        run: |
          python -m pytest tests
